[telegram]
token = "8793126374:AAG5zIBWrUOq50Ku0zjXEe8joD_JlcCDURI"
chat_id = "7860013984"

[sheets]
id_sheet = "1WcVWos3p9NJKKEpY2L1-gmKhEkZJH1FL8Hy5bNqHyRA"
gid_config = "612320365"
gid_productos = "0"
gid_pedidos = "1395505058"

[default_theme]
primary_color = "#FF4B4B"
secondary_color = "#FF6B6B"
background_color = "#FFFFFF"
text_color = "#1E1E1E"
font_family = "'Poppins', sans-serif"
