# Configuración temporal - Los secrets reales van en Streamlit Cloud
[telegram]
token = "TU_TOKEN_AQUI"
chat_id = "TU_CHAT_ID_AQUI"

[sheets]
id_sheet = "TU_ID_SHEET"
gid_config = "612320365"
gid_productos = "0"
gid_pedidos = "1395505058"

[default_theme]
primary_color = "#FF4B4B"
secondary_color = "#FF6B6B"
